Update the house routes with queries for location
haikuacademy/B11G01-airbnb-api pull request #20
Opened 2024-02-19 14:16 UTC by Asayaobi

2024-02-19 15:13 UTC, ynotrusso submitted a review, later dismissed
Please test your routes before pushing. Now you have a query that says `SELECT * FROM houses WHERE 1 = 1 WHERE location = ...` with a double `WHERE`.

2024-02-19 15:40 UTC, Asayaobi commented on routes/housesRoutes.js
> +    if (req.query.max_price) {
Thank you for the hints, Tony. After 2 cans of Leo, I think I managed to get it working.. hopefully

2024-02-20 03:21 UTC, enaros requested changes
look at the order, it is hardcoded

2024-02-20 03:51 UTC, enaros approved these changes
LGTG!

2024-02-20 03:52 UTC, merged